import { Section } from './types';

export const SECTIONS: Section[] = [
  {
    id: 'excitable-tissues',
    title: 'Basic physiological definitions. The physiology of excitable tissues',
    questions: [
      { id: 'et-1', number: 1, text: 'The subject of physiology. Biological features of living organism. Systemic approach to investigation of living organism’s properties and functions: principles of correlation, regulation, self-regulation.' },
      { id: 'et-2', number: 2, text: 'Electrogenesis in excitable tissues. Methods for membrane potentials registration. Action potential: the phases and it’s ionic mechanisms. The law "All or none".' },
      { id: 'et-3', number: 3, text: 'Types of stimulation for excitable tissues. Correlation between threshold and excitability. Change of excitability during excitation: origin. Characteristics of excitability for nerves and muscles.' },
      { id: 'et-4', number: 4, text: 'Conduction mechanism of excitement in nervous fibers. The laws of excitation propagation across nerve fibers and nerves. Experiment of Gasser-Erlanger. The types of nervous fibers according to the conduction rate.' },
      { id: 'et-5', number: 5, text: 'Mechanism of excitement conduction in synapses. Properties of a synapse. Lability and its characteristics. Types of mediators. Excitatory and inhibitory synapses.' },
      { id: 'et-6', number: 6, text: 'Types of muscular contraction. Components of a single contraction. Conditions of stepwise and tetanic contraction. Correspondence between lability, optimum and pessimum. Peculiarity of confluencing contraction in the human body. Mechanism of muscular contraction.' },
      { id: 'et-7', number: 7, text: 'Peculiarities of smooth muscles contraction: automaticity, plastic tone and others. Significance of these properties to functions of internal organs. Why do excitable tissues obey the law of "All or none"?' },
    ]
  },
  {
    id: 'neural-humoral',
    title: 'Basics of neural and humoral regulation',
    questions: [
      { id: 'nh-1', number: 1, text: 'Principles for somatic and visceral functions’ regulation. Differences and biological meaning of neural and humoral regulation, their morphological and functional features. Hormonal regulation and its role in a whole organism.' },
      { id: 'nh-2', number: 2, text: 'Outline the functions of the autonomic nervous system. The principal differences (in structure and functions) in comparison with somatic nervous system. Methods of investigation.' },
      { id: 'nh-3', number: 3, text: 'Describe the location of preganglionic and postganglionic sympathetic and parasympathetic neurons in the central nervous system and identify the nerves by which their axons leave the central nervous system.' },
      { id: 'nh-4', number: 4, text: 'Characterise the sympathetic capacities for «preparation for flight or fight» Adapting and trophic functions of the sympathetic nervous system. Orbeli’s experiment' },
      { id: 'nh-5', number: 5, text: 'The structural and physiological peculiarities of the sympathetic division of the ANS: nerve centres, efferent nerves, physiological effects.' },
      { id: 'nh-6', number: 6, text: 'The structural and physiological peculiarities of the parasympathetic division of the ANS: nerve centres, efferent nerves, physiological effects.' },
      { id: 'nh-7', number: 7, text: 'Define humoral regulation. How are all humoral factors can be classified? What is the functional significance of endocrine glands?' },
      { id: 'nh-8', number: 8, text: 'How are the human endocrine glands classified? Types of endocrine glands. What are the basic properties of hormones?' },
      { id: 'nh-9', number: 9, text: 'Hormone’s classification. The mechanism of hormone’s action on the target-cells. What physiological effects do the hormones exert on the human body?' },
      { id: 'nh-10', number: 10, text: 'How is the activity of the endocrine glands regulated? The fate of hormones in the body. Methods of functional evaluation of the endocrine glands.' },
      { id: 'nh-11', number: 11, text: 'Describe the structure of the pituitary gland. Which hormones are produced by the anterior pituitary lobe? What hormones are accumulated in the posterior pituitary lobe?' },
      { id: 'nh-12', number: 12, text: 'The structure of the thyroid gland. What hormones does the thyroid gland produce? How is the production of iodine-containing thyroid hormones controlled? The main actions of thyroid hormones.' },
      { id: 'nh-13', number: 13, text: 'The pancreatic cells serving the endocrine function. What hormones are produced in the pancreas and their physiological effects.' },
      { id: 'nh-14', number: 14, text: 'Outline the structure of the adrenal glands. Hormones produced by the adrenal cortex. Physiological effects of glucocorticoids and mineralocorticoids.' },
      { id: 'nh-15', number: 15, text: 'Hormones produced by the adrenal medulla. The physiological roles of adrenaline and noradrenaline. How is the hormone production in the adrenal medulla controlled?' },
    ]
  },
  {
    id: 'circulation',
    title: 'Circulation',
    questions: [
      { id: 'circ-1', number: 1, text: 'The systemic and pulmonary circulation. Describe the main and accessory mechanisms of the blood flow.' },
      { id: 'circ-2', number: 2, text: 'External manifestations of the cardiac activity. Name the cardiac valves and describe their functions and mechanisms. Define the epicardium, myocardium, endocardium, and pericardium.' },
      { id: 'circ-3', number: 3, text: 'What are the properties of the myocardium? Specificity of the myocardial refractory period and cardiac muscle’s contraction. The extrasystole, its types and causes.' },
      { id: 'circ-4', number: 4, text: 'The conducting system of the heart, it’s composition and meaning. The test demonstrating cardiac automaticity. The origin and gradient of automaticity.' },
      { id: 'circ-5', number: 5, text: 'The phases of the cardiac cycle. What is the significance of cardiac diastole, systole and pause? Name the features of ventricular systole and diastole. The intracardiac pressure during different phases of cardiac cycle.' },
      { id: 'circ-6', number: 6, text: 'Name the laws of cardiac activity. The Frank-Starling’s mechanism and it’s significance.' },
      { id: 'circ-7', number: 7, text: 'Innervation of the heart. How is the cardiac activity influenced by the vagus and sympathetic nerves?' },
      { id: 'circ-8', number: 8, text: 'What is afferent and efferent innervation of the heart? How is reflex control of the cardiac activity accomplished? Describe the influence of the cerebral cortex on the cardiac activity.' },
      { id: 'circ-9', number: 9, text: 'Humoral regulation of the cardiac activity. Cardiostimulating and cardioinhibiting hormonal and nonhormonal factors.' },
      { id: 'circ-10', number: 10, text: 'The Electrocardiogram and the meaning of its waves and intervals. Basic principles of the method. Clinical implementation of ECG.' },
      { id: 'circ-11', number: 11, text: 'Acoustic manifestations of the cardiac activity. What are the mechanisms and location of the apex beat? The phonocardiogram and the meaning of its oscillations. Origine of the hearts tones.' },
      { id: 'circ-12', number: 12, text: 'Stroke volume and cardiac output, their measurements and normal values. Basic principles of the echocardioraphy.' },
      { id: 'circ-13', number: 13, text: 'What are the main and accessory mechanisms of the blood flow? List the types of blood vessels. Their classification and functions.' },
      { id: 'circ-14', number: 14, text: 'Laws of vascular blood flow. The relationship between flow, pressure, and resistance in the vascular system. The Poiseuille-Hagen formula for flow in blood vessels.' },
      { id: 'circ-15', number: 15, text: 'Define the blood turnover time. What is the difference between the volume and linear blood flow?' },
      { id: 'circ-16', number: 16, text: 'The blood pressure and its main determining factors. Definitions of systolic, diastolic, pulse and mean arterial blood pressure, their norms and interpretations. Outline the technique of human arterial pressure measuring.' },
      { id: 'circ-17', number: 17, text: 'Name the constituent vessels of the microcirculatory bed. The anatomy and function of capillaries. The lymphatic system, the structure of lymphatic capillaries. The Composition and properties of the lymph. The locations of the lymph nodes and their functions.' },
      { id: 'circ-18', number: 18, text: 'Describe the venous blood flow. Determinants of the venous return? What organs and vessels serve as blood reservoirs? Their significance.' },
      { id: 'circ-19', number: 19, text: 'The mechanisms of blood redistribution in the vascular system. What are the features of the pulmonary, muscles and cerebral circulation?' },
      { id: 'circ-20', number: 20, text: 'What is the peculiarity of coronary circulation and how is it controlled?' },
      { id: 'circ-21', number: 21, text: 'How does the arterial pulse arise? How are the properties of the pulse evaluated? What is the sphygmogram?' },
      { id: 'circ-22', number: 22, text: 'The peculiarities of blood vessels innervation. What are vasoconstrictor and vasodilator nerves?' },
      { id: 'circ-23', number: 23, text: 'The vasomotor center, its location, structure, and function. What factors influence the neurons of the vasomotor centre?' },
      { id: 'circ-24', number: 24, text: 'Humoral regulation of vascular tone. List the principal vasoregulatory factors secreted by endothelial cells, and describe the function of each. The principal hormones that affect blood pressure.' },
      { id: 'circ-25', number: 25, text: 'Outline the neural mechanisms that control blood pressure and heart rate, including the receptors, afferent and efferent pathways, central integrating pathways, and effector mechanisms involved. Reflexogenic zones of the aortic arch and carotid sinus and specify their function.' },
      { id: 'circ-26', number: 26, text: 'The functional system maintaining the level optimal for metabolism of arterial blood pressure: principle characteristics and dynamic while blood pressure rising or falling.' },
      { id: 'circ-27', number: 27, text: 'What are the mechanisms of cardiovascular functional adjustment during physical activity?' },
      { id: 'circ-28', number: 28, text: 'Classification and possibilities of methods for examining of vascular tone. Reography, sphygmography.' },
    ]
  },
  {
    id: 'blood',
    title: 'Physiology of Blood',
    questions: [
      { id: 'bld-1', number: 1, text: 'The concepts of homeostasis and homeokinesis. The role of functional systems maintaining the constancy of the internal medium of the body. Blood and its place in liquid fluids of the body. Physiological functions of the blood.' },
      { id: 'bld-2', number: 2, text: 'The composition of blood. Physiological functions of the blood. The functional system maintaining the constancy of circulating blood mass. The proteins of blood plasma and their functions.' },
      { id: 'bld-3', number: 3, text: 'The osmotic pressure of blood. The functional system maintaining the constancy of the osmotic pressure of blood. Humoral adjustments of the osmotic pressure.' },
      { id: 'bld-4', number: 4, text: 'The acid-base status (pH) of blood. Draw the functional system maintaining the constancy of blood pH value.' },
      { id: 'bld-5', number: 5, text: 'Physiological functions of erythrocytes. Hemoglobin and its role.' },
      { id: 'bld-6', number: 6, text: 'The physiological functions of leucocytes. Leucocyte’s formula and it’s clinical significance.' },
      { id: 'bld-7', number: 7, text: 'The concept of hemostasis. Mechanisms of vascular platelet hemostasis, physiological functions of thrombocytes' },
      { id: 'bld-8', number: 8, text: 'The mechanisms of coagulation hemostasis. The anticoagulation mechanisms. Anticoagulants. Regulation of blood clotting.' },
      { id: 'bld-9', number: 9, text: 'The basis of blood-grouping. The rhesus (Rh) factor and rhesus conflict. Blood-typing and transfusion of blood.' },
    ]
  },
  {
    id: 'respiration',
    title: 'Physiology of Respiration',
    questions: [
      { id: 'resp-1', number: 1, text: 'The nature of respiration. What constituents of the respiratory process do you know? What is the composition of inhaled, exhaled and alveolar air? Why they are different?' },
      { id: 'resp-2', number: 2, text: 'List and describe the phases of the respiratory cycle. Classify and describe physiologically normal and clinically important various respiratory patterns.' },
      { id: 'resp-3', number: 3, text: 'The mechanisms of external inspiration and expiration. Significance of negative intrapleural pressure. The Donders model illustratin.' },
      { id: 'resp-4', number: 4, text: 'Lung volumes. Describe methods for their determination. What is pulmonary ventilation? Spyrography. Spyrometry.' },
      { id: 'resp-5', number: 5, text: 'What is the physical basis for gas diffusion throughout the whole process of respiration? Mechanisms of alveolar-capillary diffusion in the lungs.' },
      { id: 'resp-6', number: 6, text: 'Describe the mechanism of gas transport by the blood. Oxygen transport by the blood in different forms. The curve of Oxyhemoglobin dissociation.' },
      { id: 'resp-7', number: 7, text: 'How is carbon dioxide transported in the blood? What is the role of carbonic anhydrase in CO2 transport?' },
      { id: 'resp-8', number: 8, text: 'Which neurons is the respiratory centre composed of and where is it located? What are the levels of regulation of the respiratory centre activity?' },
      { id: 'resp-9', number: 9, text: 'How can the humoral regulation of the respiratory centre be proved? What are the mechanisms of the CO2 influence on the activity of the respiratory centre neurons? Describe the Frederique’s cross-circulation experiment.' },
      { id: 'resp-10', number: 10, text: 'The Functional system for maintenance of Blood Gases in the organism on the optimal for metabolism level. How is self-regulation of respiration performed?' },
      { id: 'resp-11', number: 11, text: 'How is respiratory system function under hypobaric condition? Describe mechanisms of acclimatization to altitude. What are effects of increased barometric pressure?' },
    ]
  },
  {
    id: 'energy-temp',
    title: 'Energy balance and regulation of body temperature',
    questions: [
      { id: 'etmp-1', number: 1, text: 'The concepts of assimilation and dissimilation. Nitrogen balance. Positive and negative nitrogen balance.' },
      { id: 'etmp-2', number: 2, text: 'Describe the methods of calorimetry. Direct calorimetry. Indirect calorimetry with complete gas analysis. Respiratory quotient. The respiratory quotient during muscular work.' },
      { id: 'etmp-3', number: 3, text: 'Define the concept of basal metabolic rate and the conditions to estimate it. Factors that influence the basal metabolic rate.' },
      { id: 'etmp-4', number: 4, text: 'Define the concept of total metabolism. Define the concept of working surplus. Energy expenditure under various kinds of labour.' },
      { id: 'etmp-5', number: 5, text: 'Nutrition and its role in replenishing the energy and substances losses. Assimilation of nutrients. The principles of compiling a diet.' },
      { id: 'etmp-6', number: 6, text: 'The constancy of internal milieu body temperature as a necessary condition of metabolism. The temperature scheme of human body and its daily fluctuations. Thermometry.' },
      { id: 'etmp-7', number: 7, text: 'Heat production. Metabolism as a heat source. The role of internal organs and tissues in heat production. Regulation of this process.' },
      { id: 'etmp-8', number: 8, text: 'Heat release. Forms and ways of heat release and regulation of this process. The role of sweat glands in thermoregulation processes.' },
      { id: 'etmp-9', number: 9, text: 'The functional system determining the constancy of body temperature. Analysis of its central and peripheral components.' },
      { id: 'etmp-10', number: 10, text: 'Thermoregulation under high and low environmental temperature. Hypo – and hyperthermia.' },
    ]
  },
  {
    id: 'digestion',
    title: 'Physiology of the Digestion',
    questions: [
      { id: 'dig-1', number: 1, text: 'Digestion. Functions of the digestive tract. Methods to study digestive processes.' },
      { id: 'dig-2', number: 2, text: 'Oral digestion. Which salivary glands are classified according to size and function? What enzymes does the saliva contain? The mechanism of salivation and its regulation.' },
      { id: 'dig-3', number: 3, text: 'Digestion in the stomach and its regulation. What glands are there in the gastric mucosa? What are the methods to evaluate gastric secretion? Food evacuation from the stomach.' },
      { id: 'dig-4', number: 4, text: 'Enzymes of the gastric juice. How do nutrient components affect gastric secretion? The phases of gastric secretion. What kind of motility occurs in the stomach?' },
      { id: 'dig-5', number: 5, text: 'Pancreas and its role in digestion. Regulation of pancreas juice production and excretion. What are the phases of pancreatic secretion? How can pancreatic activity be tested?' },
      { id: 'dig-6', number: 6, text: 'Liver and its role in digestion, Regulation of bile production and bile excretion, What is the role of bile in digestion? How does vesical and hepatic bile differ?' },
      { id: 'dig-7', number: 7, text: 'Small intestine and its role in digestion. Regulation of its secretory and motor activity. What enzymes does the intestinal juice contain? How are cavital and parietal digestion defined?' },
      { id: 'dig-8', number: 8, text: 'Large intestine and its role in digestion. Regulation of its secretory and motor activity. Act of defecation.' },
      { id: 'dig-9', number: 9, text: 'The physiological nature of absorption. Protein, carbohydrates and lipid absorption in the digestive tract.' },
      { id: 'dig-10', number: 10, text: 'The functional system determining the optimal for metabolism nutrients level in the body.' },
      { id: 'dig-11', number: 11, text: 'What components has the alimentary centre and what is its function? The physiological mechanisms of hunger. What are the physiological mechanisms of appetite and satiaty?' },
    ]
  },
  {
    id: 'excretion',
    title: 'Physiology of the Excretion',
    questions: [
      { id: 'exc-1', number: 1, text: 'Kidneys as the basic executive mechanism of the functional system determining the osmotic pressure of blood optimal for the body metabolism.' },
      { id: 'exc-2', number: 2, text: 'Nephron as the functional unit of kidneys. Peculiarities of the renal blood.' },
      { id: 'exc-3', number: 3, text: 'The physiological mechanism of urine formation: ultrafiltration. Regulation of glomerular ultrafiltration.' },
      { id: 'exc-4', number: 4, text: 'The reabsorptive process in a nephron: the obligatory and optional re-absorption in the convoluted tubules and collecting duct. Regulation of reabsorption.' },
      { id: 'exc-5', number: 5, text: 'The countercurrent multiplication mechanism of Henle\'s loop. Its physiological significance.' },
      { id: 'exc-6', number: 6, text: 'The physiological mechanism of urine formation: secretory process. Neural and humoral regulation of urine formation.' },
      { id: 'exc-7', number: 7, text: 'Methods to determine the glomerular filtration rate, reabsorption, and secretion in humans.' },
      { id: 'exc-8', number: 8, text: 'Clinical methods of examination of kidneys and urine analysis.' },
      { id: 'exc-9', number: 9, text: 'Non-excretory functions of kidneys: participation in determining the acid - base status of blood; maintaining of the blood pressure; participatiois in haemopoiesis.' },
      { id: 'exc-10', number: 10, text: 'The urine excretion (micturition) and its regulation.' },
    ]
  },
  {
    id: 'cns',
    title: 'Physiology of the Central nervous system',
    questions: [
      { id: 'cns-1', number: 1, text: 'The functional significance of the central nervous system. The anatomo-histological and physiological unit of the nervous system. The structure of the neuron. Types of neurons in the CNS. Types of synapses and their role.' },
      { id: 'cns-2', number: 2, text: 'The reflex arcs and their components. Classification. Name the types of unconditioned reflexes. Unconditioned reflexes in men, their classification and methods for evaluation.' },
      { id: 'cns-3', number: 3, text: 'How is the nerve center defined and what is its role? The basic principles of nerve centers functioning.' },
      { id: 'cns-4', number: 4, text: 'The principles of excitation‘s propagation in the CNS.' },
      { id: 'cns-5', number: 5, text: 'The origin and classification of inhibition in the CNS. Historical background, synaptic basis and mechanisms of inhibition in CNS. Experiment of Sechenov\'s inhibition. Inhibition mechanisms: hypopolarizing, long depolarizing, postsynaptic, presynaptic, pessimal. Reciprocal, antidromal and reticular inhibition.' },
      { id: 'cns-6', number: 6, text: 'Classification and characteristic of methods for studying of CNS functions.' },
      { id: 'cns-7', number: 7, text: 'The physiological origin of electroencephalography. Name and describe major EEG rhythms. The role and clinical implementation of EEG. Evoked potentials.' },
      { id: 'cns-8', number: 8, text: 'The physiology of spinal cord. What is the physiological role of the anterior and posterior spinal roots? Regulation of muscular tone at the level of spinal cord. What reflex centres are located in the spinal cord? The origin of spinal shock.' },
      { id: 'cns-9', number: 9, text: 'The physiology of the medulla oblongata. What reflex centres are present in the medulla oblongata? Name the features of the reticular formation neurons. What is it’s physiological role?' },
      { id: 'cns-10', number: 10, text: 'Regulation of tone of skeletal muscles by spinal cord. Role of proprioreceptors: the intrafusal muscular fibers (spindles) and the Golgi\'s tendon organs. Role of alpha- and gamma-motoneurons.' },
      { id: 'cns-11', number: 11, text: 'The physiology structure of the mid-brain. What are the roles of the anterior and posterior quadrigeminal bodies? Position finding reflexes. Decerebrate rigidity: the origin and symptoms.' },
      { id: 'cns-12', number: 12, text: 'The physiology and the structure of the diencephalon. What is the role of the thalamus? What structures belong to the basal nuclei and what are their roles?' },
      { id: 'cns-13', number: 13, text: 'Functions of cerebellum in posture and muscular tone regulation. What motor disorders are observed in cerebellar lesions?' },
      { id: 'cns-14', number: 14, text: 'The major areas of the cerebral cortex and their assignments. The symptoms of distractions of extrapyramid system.' },
    ]
  },
  {
    id: 'sensory',
    title: 'General and special sensory physiology',
    questions: [
      { id: 'sens-1', number: 1, text: 'The functional structure and constituents of the analyzer. Pavlov\'s theory of analyzers. Define the concepts of a sensory organ, analyzer, sensory system, and sensation.' },
      { id: 'sens-2', number: 2, text: 'Describe the receptor and its function. Receptor’s classifications. The physiological properties of receptors.' },
      { id: 'sens-3', number: 3, text: 'The skin receptors: tactile, pressure, warm, cold. Physiology of skin reception.' },
      { id: 'sens-4', number: 4, text: 'The taste and olfactory analyzers.' },
      { id: 'sens-5', number: 5, text: 'Neurophysiology of pain. Nociceptors: classification and characteristic. The functional system determining optimal organs and tissues body functioning including pain sensation. The nociceptive and antinociceptive systems.' },
      { id: 'sens-6', number: 6, text: 'Physiology of antinociceptive mechanisms. Clinical implementation of antinociceptive external factors.' },
      { id: 'sens-7', number: 7, text: 'The functional structure of the visual analyzer. Draw the light waves passes through the optic eyeball system. Structure of the retina. Accommodation and its mechanisms. Refraction abnormalities and their correction.' },
      { id: 'sens-8', number: 8, text: 'The roles of rods and cones in vision. Describe the mechanism of light sensation. Binocular vision. The theory of colour vision.' },
      { id: 'sens-9', number: 9, text: 'The functioning and structure of the acoustic analyzer. The vestibular analyzer.' },
    ]
  },
  {
    id: 'higher-cns',
    title: 'Higher functions of the Central nervous system',
    questions: [
      { id: 'hcns-1', number: 1, text: 'How is the higher nervous activity understood? The definition of conditioned reflex. Classification of conditioned reflexes. Describe major differences between, and mechanisms of conditioned and unconditioned reflexes.' },
      { id: 'hcns-2', number: 2, text: 'Inhibition of conditioned reflex: classification and biological role. What are the orientation reflexes? What are their features?' },
      { id: 'hcns-3', number: 3, text: 'The Instinct, examples of instincts. What is defined as the dynamic stereotype?' },
      { id: 'hcns-4', number: 4, text: 'What are the implications of excitation-inhibition interaction in the CNS for the vital activity of the body? List the types of induction relations of excitation to inhibition.' },
      { id: 'hcns-5', number: 5, text: 'Types of the higher nervous activity. The Pavlovian types of the higher nervous activity in animals. Methods for HNA types determination. The types of the higher nervous activity in man.' },
      { id: 'hcns-6', number: 6, text: 'The central architectonic of behavioral acts on the basis of the P.K.Anokhin’s theory of functional systems: main stages - useful adapting result, afferent synthesis, bringing solution, efferent synthesis, acceptor of the effect result. Autonomic and endocrine arrangement of the behavioral act.' },
      { id: 'hcns-7', number: 7, text: 'Motivation (drive) and memory as components of afferent synthesis. Types of motivation. Mechanisms of long-term and short-term memory. Learning and memory.' },
      { id: 'hcns-8', number: 8, text: 'Systemic organization of emotional reactions. Biological role of emotions, mechanisms and theories. Emotional stress: sensitivity and resistance to it. Prophylaxis of emotional stress.' },
      { id: 'hcns-9', number: 9, text: 'Systemic organization of sex functions. Sex hormones and their functions. Regulatory mechanisms of sex functions. Interrelation of social and biological functions in sexual behavior.' },
      { id: 'hcns-10', number: 10, text: 'Physiology of sleep. Biological significance and structure of sleep. Modern theories concerning the sleep nature and sleep mechanisms. Sleep-therapy.' },
    ]
  }
];